<?php

/**
 * NoClass™ PHP Procedural Framework
 *
 * Copyright 2024-2026 Danny Mbanginu
 *
 * Licensed under the Apache License, Version 2.0.
 * See the LICENSE file for details.
 */

function filemap_cache_dir(): string
{
    $dir = BASE_PATH . '/storage/cache';

    if (!is_dir(BASE_PATH . '/storage')) {
        $dir = BASE_PATH . '/cache';
    }

    return $dir;
}

function filemap_cache_file(): string
{
    return rtrim(filemap_cache_dir(), '/\\') . '/filemap.php';
}

function filemap_base_path(): string
{
    return rtrim(str_replace('\\', '/', BASE_PATH), '/');
}

function filemap_to_relative(string $path): string
{
    $path = str_replace('\\', '/', $path);
    $base = filemap_base_path();

    if (strpos($path, $base . '/') === 0) {
        $path = substr($path, strlen($base) + 1);
    }

    return ltrim($path, '/');
}

function filemap_to_absolute(string $relative): string
{
    return rtrim(BASE_PATH, '/\\') . DIRECTORY_SEPARATOR . str_replace(
        ['/', '\\'],
        DIRECTORY_SEPARATOR,
        ltrim($relative, '/\\')
    );
}

function filemap_build(array $dirs): array
{
    $map = [];

    foreach ($dirs as $dir) {
        if (!is_dir($dir)) {
            continue;
        }

        $it = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($it as $file) {
            if (!$file->isFile()) {
                continue;
            }

            if (strtolower($file->getExtension()) !== 'php') {
                continue;
            }

            $fullPath = $file->getPathname();
            $relative = filemap_to_relative($fullPath);

            $key = filemap_key_from_relative($relative);

            if (isset($map[$key])) {
                trigger_error(
                    'Duplicate filemap key detected: ' . $key,
                    E_USER_WARNING
                );
            } 
            
            $map[$key] = $relative;
        }
    }

      

    return $map;
}

/**
 * Convert a relative file path into a filemap key.
 *
 * Examples:
 *
 * controllers/Home.php-> Home
 * models/User.php -> User
 * middleware/Auth.php -> Auth
 * modules/blog/controllers/Post.php -> blog/controllers/Post
 * modules/admin/models/User.php -> admin/models/User
 */
function filemap_key_from_relative(string $relative): string
{
    // Normalize separators
    $key = str_replace('\\', '/', $relative);

    // Remove .php extension
    if (substr($key, -4) === '.php') {
        $key = substr($key, 0, -4);
    }

    // Remove only the first framework folder
    static $prefixes = [
        'controllers/',
        'models/',
        'views/',
        'middleware/',
        'lib/',
        'modules/',
    ];

    foreach ($prefixes as $prefix) {
        if (strpos($key, $prefix) === 0) {
            $key = substr($key, strlen($prefix));
            break;
        }
    }

    return $key;
}

function filemap_ensure_cache_dir(): bool
{
    $dir = filemap_cache_dir();

    if (is_dir($dir)) {
        return true;
    }

    return @mkdir($dir, 0775, true);
}

function filemap_write_cache(string $file, array $payload): bool
{
    if (!filemap_ensure_cache_dir()) {
        return false;
    }

    $php = "<?php\n\n// Auto-generated by NoClass filemap. Do not edit manually.\nreturn "
        . var_export($payload, true)
        . ";\n";

    $tmp = $file . '.tmp';

    if (@file_put_contents($tmp, $php, LOCK_EX) === false) {
        return false;
    }

    return @rename($tmp, $file);
}

function filemap_load_cache(string $file)
{
    if (!is_file($file)) {
        return null;
    }

    return require $file;
}

function filemap_cache_is_valid($payload): bool
{
    if (!is_array($payload)) {
        return false;
    }

    $meta = $payload['meta'] ?? [];

    if (($meta['platform'] ?? '') !== PHP_OS_FAMILY) {
        return false;
    }

    if (($meta['base_path'] ?? '') !== filemap_base_path()) {
        return false;
    }

    return true;
}

function filemap_rebuild_all(): array
{
    $payload = [
        'meta' => [
            'generated_at' => time(),
            'base_path'    => filemap_base_path(),
            'platform'     => PHP_OS_FAMILY,
            'path_mode'    => 'relative',
        ],

        'libs'        => filemap_build([BASE_PATH . '/lib/']),
        'views'       => filemap_build([BASE_PATH . '/views/']),
        'models'      => filemap_build([BASE_PATH . '/models/']),
        'modules'     => filemap_build([BASE_PATH . '/modules/']),
        'middleware'  => filemap_build([BASE_PATH . '/middleware/']),
        'controllers' => filemap_build([BASE_PATH . '/controllers/']),
    ];

    filemap_write_cache(filemap_cache_file(), $payload);

    return $payload;
}

function filemap_expand_paths(array $map): array
{
    $expanded = [];

    foreach ($map as $key => $relative) {
        $expanded[$key] = filemap_to_absolute($relative);
    }

    return $expanded;
}

function filemap_boot_globals(): void
{
    $cacheFile = filemap_cache_file();

    $autoRebuild = defined('FILEMAP_AUTO_REBUILD')
        ? (bool) FILEMAP_AUTO_REBUILD
        : false;

    if ($autoRebuild) {
        $payload = filemap_rebuild_all();
    } else {
        $payload = filemap_load_cache($cacheFile);

        if (!filemap_cache_is_valid($payload)) {
            $payload = filemap_rebuild_all();
        }
    }

    $GLOBALS['libs']        = filemap_expand_paths($payload['libs'] ?? []);
    $GLOBALS['views']       = filemap_expand_paths($payload['views'] ?? []);
    $GLOBALS['models']      = filemap_expand_paths($payload['models'] ?? []);
    $GLOBALS['modules']     = filemap_expand_paths($payload['modules'] ?? []);
    $GLOBALS['middleware']  = filemap_expand_paths($payload['middleware'] ?? []);
    $GLOBALS['controllers'] = filemap_expand_paths($payload['controllers'] ?? []);
}